#!/usr/bin/env python
import sys, urllib3
 
url = 'http://www.rcsb.org/pdb/rest/search'
 
queryText =
<orgPdbQuery>
<queryType>org.pdb.query.simple.MolecularWeightQuery</queryType>
<description>Molecular Weight Search : Min Molecular Weight=11000.0 Max Molecular Weight=44000.0</description>
<entity.formula_weight.min>11000</entity.formula_weight.min>
<entity.formula_weight.max>44000</entity.formula_weight.max>
</orgPdbQuery>

query2 =
<orgPdbQuery>
<queryType>org.pdb.query.simple.ChainTypeQuery</queryType>
<description>Chain Type Search : Contains Protein=Y, Contains DNA=N, Contains RNA=N, Contains DNA/RNA Hybrid=N</description>
<containsProtein>Y</containsProtein>
<containsDna>N</containsDna>
<containsRna>N</containsRna>
<containsHybrid>N</containsHybrid>
</orgPdbQuery>
 


print "query:\n", queryText
print "querying PDB...\n"
req = urllib3.Request(url, data=queryText+query2)
f = urllib3.urlopen(req)
result = f.read()
 
if result:
   print "Found number of PDB entries:",result.count('\n')
else:
   print "Failed to retreive results"
