#!/usr/bin/env python
import requests
 
url = 'http://www.rcsb.org/pdb/rest/search'
 
queryText =
<orgPdbQuery>
<queryType>org.pdb.query.simple.MolecularWeightQuery</queryType>
<description>Molecular Weight Search : Min Molecular Weight=11000.0 Max Molecular Weight=37000.0</description>
<entity.formula_weight.min>11000</entity.formula_weight.min>
<entity.formula_weight.max>37000</entity.formula_weight.max>
</orgPdbQuery>

query2 =
<orgPdbQuery>
<queryType>org.pdb.query.simple.ChainTypeQuery</queryType>
<description>Chain Type Search : Contains Protein=Y, Contains DNA=N, Contains RNA=N, Contains DNA/RNA Hybrid=N</description>
<containsProtein>Y</containsProtein>
<containsDna>N</containsDna>
<containsRna>N</containsRna>
<containsHybrid>N</containsHybrid>
</orgPdbQuery>
 


print("query:\n" + queryText)
print("querying PDB...\n")
header = {'Content-Type': 'application/x-www-form-urlencoded'}
response = requests.post(url, data=queryText, headers=header)
 
if response.status_code == 200:
   print("Found %d number of PDB entries:" % len(response.text))
else:
   print("Failed to retreive results")
