#!/usr/bin/env bash

###minimum alpha sphere filter
alphas=80

###This top block of code just runs fpocket iteratively over
###all available PDB's in the PDB directory
for i in $(ls ../PDB/*.pdb); do
	fpocket -f ../PDB/$i -i $alphas
done

###This block detects which fpocket outputs don't have pockets
###and deletes their respective directories
shopt -s nullglob
for d in ../PDB/*/pockets/; do
   set -- "$d"/*
   (( $# )) && continue
   rm -rf -- "${d%/pockets/}"
done

###call the python function to clear out the unused pdbs
function call_python { python cleanup-pdbs.py; }
call_python
